### ISSUE TITLE
API returns "Internal server error"

### ISSUE THREAD

**Issue by michalcz17** [DKFN/simrail-community-api#1]
After opening the link provided in docs, the API returns "Internal server error"
![image](https://github.com/DKFN/simrail-community-api/assets/71758861/c1164b8d-722f-4c2e-ae1d-6f071159bf6a)

**Comment by DKFN** [comment]
Hello,
I have discontunued support of this API for a few months but you can access the new version made by CrypterEmerald here:

https://simrail-edr.emeraldnetwork.xyz/train/fr1/1443

This is the API behind this interface: https://edr.simrail.app/fr1/trains

Full source code is accessible for the backend here: https://github.com/simrail/EDR/tree/master/backend

I hope this will help you in your project :)

**Comment by michalcz17** [comment]
Thank you
